language: elixir

notifications:
  email: false

elixir:
  - 1.8.2

otp_release:
  - 21.0

script:
  - mix test
  - mix dialyzer --halt-exit-status

cache:
  directories:
    - priv/plts
    - _build
    - deps
