language: elixir

notifications:
  email: false

elixir:
  - 1.8.2

otp_release:
  - 21.0

matrix:
  - TESTS=1
  - DIALYZER=1

script:
  - if [ $TESTS -eq "1" ]; then mix test; else mix dialyzer --halt-exit-status; fi

cache:
  directories:
    - priv/plts
    - _build
    - deps
