language: elixir

notifications:
  email: false

elixir:
  - 1.8.2

otp_release:
  - 21.0

matrix:
  include:
    - elixir: '1.6'
      otp_release: '19.0'
    - elixir: '1.8'
      otp_release: '21.0'

script:
  - mix test
  - mix dialyzer --halt-exit-status

cache:
  directories:
    - priv/plts
    - _build
    - deps
